spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/paymentdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:EminSamad}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:f5cddac2cacdcb}
    password: ${MAIL_PASSWORD:6074e2befeac3f}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

security:
  jwt:
    secret: ${JWT_SECRET:9a7f3d2c4b6e8f1a9c7d5e3f2b1a4c6d8e9f1a2b3c4d5e6f7a8b9c0d1e2f3a4}
    expiration: ${JWT_EXPIRATION:3600000}